create table user_category
(
    id                  bigint generated by default as identity unique,
    name                varchar(10) not null,
    discount_percentage int default 0
);

insert into user_category (name, discount_percentage)
values ('ADULT', 0),
       ('CHILD', 10),
       ('SENIOR', 15),
       ('STUDENT', 20);

create table genre
(
    id   bigint generated by default as identity unique,
    name varchar(20) not null
);

insert into genre (name)
values ('THRILLER'),
       ('HORROR');

create table room_type
(
    id         bigint generated by default as identity unique,
    name       varchar(10)   not null,
    seat_price numeric(5, 2) not null
);

insert into room_type (name, seat_price)
values ('STANDARD', 2.5),
       ('PREMIUM', 6);

create table city
(
    id   bigint generated by default as identity unique,
    name varchar(50) not null unique
);

insert into city (name)
values ('Minsk');

create table movie
(
    id                  bigint generated by default as identity unique,
    name                varchar(100)  not null unique,
    duration_in_minutes int           not null,
    description         varchar(1000),
    price               numeric(5, 2) not null,
    age_rating          int           not null,
    rating              decimal,
    image_url           varchar(1000)
);

insert into movie (duration_in_minutes, name, description, price, age_rating, rating, image_url)
values (108, 'Test movie', 'Desc test', 2, 1, 10, 'fjeoiivjc');

create table movie_image
(
    id       bigint generated by default as identity unique,
    url      varchar(200)                 not null unique,
    movie_id bigint references movie (id) not null
);

insert into movie_image (url, movie_id)
values ('some_movie_url', 1);


create table movies_genres_link
(
    movie_id bigint references movie (id) not null,
    genre_id bigint references genre (id) not null
);

insert into movies_genres_link (movie_id, genre_id)
values (1, 1),
       (1, 2);

create table cinema
(
    id      bigint generated by default as identity unique,
    name    varchar(50)                 not null unique,
    address varchar(300)                not null,
    city_id bigint references city (id) not null,
    email   varchar(60)                 not null unique,
    phone   varchar(60)                 not null
);

insert into cinema (name, address, city_id, email, phone)
values ('Test', 'Test address', 1, 'test@test', '+000000000');

create table movie_room
(
    id           bigint generated by default as identity unique,
    capacity     int                              not null,
    room_type_id bigint references room_type (id) not null,
    cinema_id    bigint references cinema (id)    not null
);

insert into movie_room (capacity, room_type_id, cinema_id)
values (1, 1, 1);

create table seat
(
    id            bigint generated by default as identity unique,
    row_number    int                               not null,
    place_number  int                               not null,
    movie_room_id bigint references movie_room (id) not null
);

insert into seat (row_number, place_number, movie_room_id)
values (1, 1, 1);

create table users
(
    id                     bigint generated by default as identity unique,
    first_name             varchar(30)                          not null,
    last_name              varchar(30)                          not null,
    user_name              varchar(60)                          not null unique,
    email                  varchar(60)                          not null,
    phone                  varchar(21)                          not null,
    password               varchar(100)                         not null,
    address                varchar(200),
    city_id                bigint references city (id)          not null,
    registration_date_time timestamp                            not null,
    birth_date             date,
    category_id            bigint references user_category (id) not null,
    role                   int default 1
);

insert into users (first_name, last_name, user_name, email, phone, password, city_id, registration_date_time,
                   category_id, role)
values ('A', 'B', 'test', 'a@a', '4364364354', 'jfd2394ucf923urhcf', 1, '2022-01-08T12:30:00', 1, 1);

create table event
(
    id              bigint generated by default as identity unique,
    start_date_time timestamp                         not null,
    movie_id        bigint references movie (id)      not null,
    event_status    int                               not null,
    movie_room_id   bigint references movie_room (id) not null
);

insert into event (start_date_time, movie_id, event_status, movie_room_id)
values ('2022-01-08T12:30:00', 1, 0, 1);

create table orders
(
    id                 bigint generated by default as identity unique,
    creation_date_time timestamp                    not null,
    overall_price      numeric(5, 2)                not null,
    user_id            bigint references users (id) not null,
    order_status       int                          not null,
    event_id           bigint references event (id) not null
);

insert into orders (creation_date_time, overall_price, user_id, order_status, event_id)
values ('2022-01-08T12:30:00', 0.0, 1, 0, 1);

create table weather
(
    id          bigint generated by default as identity unique,
    city_id     bigint references city (id) not null,
    date_time   timestamp                   not null,
    temperature decimal                     not null,
    feels_like  decimal                     not null,
    pressure    decimal                     not null,
    humidity    decimal                     not null,
    min_temp    decimal                     not null,
    max_temp    decimal                     not null,
    visibility  int                         not null,
    wind_speed  decimal                     not null,
    wind_degree decimal                     not null,
    cloudiness  decimal                     not null
);

insert into weather (city_id, date_time, temperature, feels_like, pressure, humidity, min_temp, max_temp, visibility,
                     wind_speed, wind_degree, cloudiness)
values (1, '2022-01-08T12:30:00', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
       (1, '2022-03-08T12:30:00', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1);

create table ticket
(
    id       bigint generated by default as identity unique,
    price    numeric(5, 2)                 not null,
    seat_id  bigint references seat (id)   not null,
    order_id bigint references orders (id) not null
);

create table audit
(
    id                  bigint generated by default as identity,
    class_name          varchar(255) not null,
    method_name         varchar(255) not null,
    args                text         not null,
    return_value        text,
    exception           varchar(255),
    execution_time_nano bigint       not null,
    invocation_time     timestamp    not null
);